version: "3.7"
services:
  api:
    build: .
    command: ['./node_modules/.bin/nodemon']
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json