version: "3.7"
services:
  api:
    build:
      context: .
      target: tester
    command: ['./node_modules/.bin/nodemon']
    depends_on:
      - redis
    env_file: './.env'
    ports:
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./locales:/app/locales
      - ../coverages/kapi:/app/coverage/lcov-report
      - ./nodemon.json:/app/nodemon.json
      - ./.git:/app/.git:ro
  redis:
    image: 'redis:alpine'
